= Minimal reporting guideline for research involving eye tracking

This repository contains the current version of the "xref:paper.asciidoc[Minimal reporting guideline for research involving eye tracking]" paper, and is meant to serve as a forum for continuous evolution of the document, as well as discussion surrounding it. Please contribute by means of starting a link:https://github.com/dcnieho/ET_reporting_guideline/discussions[discussion], or opening a link:https://github.com/dcnieho/ET_reporting_guideline/pulls[pull request]. If you think there is an issue with the current text, notify us by opening an link:https://github.com/dcnieho/ET_reporting_guideline/issues[issue].

=== Citation
When using this guideline, please cite the latest published version:

Dunn, M.J., Alexander, R.G., Amiebenomo, O.M., Arblaster, G., Atan, D., Erichsen, J.T., Ettinger, U., Giardini, M.E., Gilchrist, I.D., Hamilton, R., Hessels, R.S., Hodgins, S., Hooge, I.T.C., Jackson, B.S., Lee, H., Macknik, S.L., Martinez-Conde, S., McIlreavy, L., Muratori, L.M., Niehorster, D.C., Nyström, M., Otero-Millan, J., Schlüssel, M.M., Self, J.E., Singh, T., Smyrnis, N., Sprenger, A. (accepted). Minimal reporting guideline for research involving eye tracking (2023 edition). Behavior Research Methods.

BibTeX:
[source,bibtex]
----
@article{dunn2023guidelines,
  author = {Dunn, M. J. and Alexander, R. G. and Amiebenomo, O. M. and Arblaster, G. and Atan, D. and Erichsen, J. T. and Ettinger, U. and Giardini, M. E. and Gilchrist, I. D. and Hamilton, R. and Hessels, R. S. and Hodgins, S. and Hooge, I. T. C. and Jackson, B. S. and Lee, H. and Macknik, S. L. and Martinez-Conde, S. and McIlreavy, L. and Muratori, L. M. and Niehorster, D. C. and Nystr{\"o}m, M. and Otero-Millan, J. and Schl{\"u}ssel, M. M. and Self, J. E. and Singh, T. and Smyrnis, N. and Sprenger, A.},	
  title = {Minimal reporting guideline for research involving eye tracking (2023 edition)},
  journal = {Behavior Research Methods},
  year = {accepted}
}
----

Further relevant considerations may be found in
link:https://doi.org/10.3758/S13428-021-01762-8[Holmqvist, K., Örbom, S. L., Hooge, I. T. C., Niehorster, D. C., Alexander, R. G., Andersson, R., Benjamins, J. S., Blignaut, P., Brouwer, A.-M., Chuang, L. L., Dalrymple, K. A., Drieghe, D., Dunn, M. J., Ettinger, U., Fiedler, S., Foulsham, T., van der Geest, J. N., Hansen, D. W., Hutton, S. B., ... Hessels, R. S. (2023). Eye tracking: empirical foundations for a minimal reporting guideline. Behavior Research Methods, 55(1), 364–416. doi: 10.3758/S13428-021-01762-8]

BibTeX:
[source,bibtex]
----
@article{holmqvist2022guidelines,
  author = {Holmqvist, K. and {\"O}rbom, S. L. and Hooge, I. T. C. and Niehorster, D. C. and Alexander, R. G. and Andersson, R. and Benjamins, J. S. and Blignaut, P. and Brouwer, Anne-Marie and Chuang, L. L. and Dalrymple, K. A. and Drieghe, D. and Dunn, M. J. and Ettinger, U. and Fiedler, S. and Foulsham, T. and van der Geest, J. N. and Hansen, D. W. and Hutton, S. and Kasneci, E. and Kingstone, A. and Knox, P. C. and Kok, E. M. and Lee, H. and Lee, J. Y. and Lepp{\"a}nen, J. M. and Macknik, S. and Majaranta, P. and Martinez-Conde, S. and Nuthmann, A. and Nystr{\"o}m, M. and Orquin, J. L. and Otero-Millan, J. and Park, S. Y. and Popelka, S. and Proudlock, F. and Renkewitz, F. and Roorda, A. J. and Schulte-Mecklenbeck, M. and Sharif, B. and Shic, F. and Shovman, M. and Thomas, M. G. and Venrooij, W. and Zemblys, R. and Hessels, R. S.},	
  title = {Eye tracking: empirical foundations for a minimal reporting guideline},
  journal = {Behavior Research Methods},
  doi = {10.3758/s13428-021-01762-8},
  year = {2022}
}
----

=== Previous verions
A complete list of previous published versions of the guideline:

2023. Dunn, M.J., Alexander, R.G., Amiebenomo, O.M., Arblaster, G., Atan, D., Erichsen, J.T., Ettinger, U., Giardini, M.E., Gilchrist, I.D., Hamilton, R., Hessels, R.S., Hodgins, S., Hooge, I.T.C., Jackson, B.S., Lee, H., Macknik, S.L., Martinez-Conde, S., McIlreavy, L., Muratori, L.M., Niehorster, D.C., Nyström, M., Otero-Millan, J., Schlüssel, M.M., Self, J.E., Singh, T., Smyrnis, N., Sprenger, A. (accepted). Minimal reporting guideline for research involving eye tracking (2023 edition). Behavior Research Methods.
